// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dyadMdFOCuS
List dyadMdFOCuS(Rcpp::NumericMatrix data, std::string method, std::string cost, bool cand_nb, bool opt_changes, bool opt_costs, bool cands, unsigned int qmin);
RcppExport SEXP _dyadicMdFOCuS_dyadMdFOCuS(SEXP dataSEXP, SEXP methodSEXP, SEXP costSEXP, SEXP cand_nbSEXP, SEXP opt_changesSEXP, SEXP opt_costsSEXP, SEXP candsSEXP, SEXP qminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type cand_nb(cand_nbSEXP);
    Rcpp::traits::input_parameter< bool >::type opt_changes(opt_changesSEXP);
    Rcpp::traits::input_parameter< bool >::type opt_costs(opt_costsSEXP);
    Rcpp::traits::input_parameter< bool >::type cands(candsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type qmin(qminSEXP);
    rcpp_result_gen = Rcpp::wrap(dyadMdFOCuS(data, method, cost, cand_nb, opt_changes, opt_costs, cands, qmin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dyadicMdFOCuS_dyadMdFOCuS", (DL_FUNC) &_dyadicMdFOCuS_dyadMdFOCuS, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_dyadicMdFOCuS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
