# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dyadMdFOCuS
#'
#' @description Single Changepoint Detection using methods: MdFOCuS0 and MdFOCuS.
#' @param data is a matrix of data (n rows x p-columns, where p - dimension, n - length).
#' @param method is the algorithm: 'FOCuS0'or 'FOCuS'.
#' @param cost is the type of cost: 'gauss' or 'poisson'.
#' @param common_difference_step is the beta parameter for 'next'.
#' @param common_ratio_step is the alpha parameter for 'next'.
#' @param first_step_qhull is the parameter for the first next (next = first_step_qhull + p+1).
#' @param cand_nb is the boolean parameter ('cand_nb=true' => get candidate number)
#' @param opt_changes is the boolean parameter ('opt_changes=true' => get optimal changes)
#' @param opt_costs is the boolean parameter ('opt_costs=true' => get optimal costs)
#' @param cands is the boolean parameter ('cands=true' => get candidates)
#'
#' @return a list of  elements  = (changes, means, UnpenalizedCost, NumberOfCandidates).
#'
#' \describe{
#' \item{\code{change}}{is the changepoint.}
#' \item{\code{cost}}{is a number equal to the segmentation cost.}
#' \item{\code{pre_change_mean}}{is the vector of pre-change means for the p-variate time series.}
#' \item{\code{post_change_mean}}{is the vector of post-change means for the p-variate time series.}
#' \item{\code{nb_candidates}}{is a number of candidates at time n.}
#' \item{\code{candidates}}{is a list of candidates at each at time n.}
#' \item{\code{nb_candidates_at_time}}{is a list of candidatenumber at each iteration.}
#' \item{\code{opt_changes_at_time}}{is a list of optimal changes at each iteration.}
#' \item{\code{opt_costs_at_time}}{is a list of coptimal costs (without constant B') at each iteration.}
#' }
#' @examples
#' 
#' set.seed(21)
#' N <- 25
#' P <- 2
#' Change <- N %/% 2
#' theta0 <-  rep(0, P)
#' #Data generation
#' ##the time series with one change
#' ts_gauss <- generate_ts(type = "gauss", p = P, n = N, changes = Change, means = matrix(c(theta0, theta0 + 5), nrow = P))
#' ts_poisson <- generate_ts(type = "poisson", p = P, n = N, changes = Change,  means = matrix(c(theta0 + 1, theta0 + 5), nrow = P))
#' ##the time series with one change
#' ts_gauss0 <- generate_ts(type = "gauss", p = P, n = N, changes = NULL, means = matrix(0, ncol = 1, nrow = P))
#' ts_poisson0 <- generate_ts(type = "poisson", p = P, n = N, changes = NULL, means = matrix(1, ncol = 1, nrow = P))
#' dyadMdFOCuS(ts_gauss, method ='FOCuS0', qmin = 2)
NULL

dyadMdFOCuS <- function(data, method = "FOCuS0", cost = "gauss", cand_nb = FALSE, opt_changes = FALSE, opt_costs = FALSE, cands = FALSE, qmin = 3L) {
    .Call(`_dyadicMdFOCuS_dyadMdFOCuS`, data, method, cost, cand_nb, opt_changes, opt_costs, cands, qmin)
}

